# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: Prod # Updated namespace
  postfix: 001 # Updated postfix
  location: eastus # Updated location

  environment: Prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # For pipeline reference
  resource_group: default_resource_group
  aml_workspace: FitwellWorkspace
  application_insights: fitwellworkspa2102931028
  key_vault: fitwellworkspa3632316330
  container_registry: 34654afcd50f4b2f97a0dc312da94dff
  storage_account: fitwellworkspa3991914525




